### PR TITLE
fix(package.json): upgrade logseq sdk

### PR DESCRIPTION
**Pull request by CharlesChiuGit**
This improves loading time.

### CODE REVIEW

**Review by pengx17 — APPROVED** [review]
LGTM. Btw if you want to have a new version published, you should use "fix" in the commit message instead of "chore".

**Comment by CharlesChiuGit** [comment]
> LGTM. Btw if you want to have a new version published, you should use "fix" in the commit message instead of "chore".

Aha, noted! tks!

**Comment by pengx17** [comment]
@CharlesChiuGit it looks like you did not commit changes in lock file. Can you file another pr to fix it?

**Comment by CharlesChiuGit** [comment]
ok, wait a sec!

**Pull request merged**
